### ISSUE TITLE
Exporting `main` conflicts with rust's entrypoint

### ISSUE THREAD

**Issue by micaelbergeron** [extism/extism#166]
When creating a plugin from the Rust PDK, you cannot export a `main` function as there will always be a `main` function in the output wasm module.

```
#[plugin_fn]
pub fn main(input: Vec<u8>) -> FnResult<Json<WidgetSchema>> {
  …
}
```

Trying to call this using `extism` cli will error out with

```
venv ❯ WASMTIME_BACKTRACE_DETAILS=1 extism call --input "abcdef" target/wasm32-unknown-unknown/release/mural_rust.wasm main
Traceback (most recent call last):
  File "/home/mbergeron/git/mural.co/mdk-env/mural-extism/venv/bin/extism", line 8, in <module>
    sys.exit(main())
  File "/home/mbergeron/git/mural.co/mdk-env/mural-extism/venv/lib/python3.8/site-packages/extism_cli/__init__.py", line 602, in main
    r = plugin.call(args.function, input, parse=None)
  File "/home/mbergeron/git/mural.co/mdk-env/mural-extism/venv/lib/python3.8/site-packages/extism/extism.py", line 288, in call
    self._check_error(
  File "/home/mbergeron/git/mural.co/mdk-env/mural-extism/venv/lib/python3.8/site-packages/extism/extism.py", line 247, in _check_error
    raise Error(_ffi.string(error).decode())
extism.extism.Error: Call failed

Caused by:
    expected 2 arguments, got 0
```

Renaming the function to `init` fixed the issue, so there might be some sort of compile time warning or doc to explain this workaround.

**Comment by nilslice** [comment]
@micaelbergeron - thanks for reporting this! We should be able to add some compile-time error reporting here, so the `#[plugin_fn]` macro catches the use of `main` here vs. waiting until the module is executed for a failure.

**Comment by nilslice** [comment]
@micaelbergeron, extism/rust-pdk#12 has a fix for this, where your plugin will fail to compile, and a (hopefully) helpful message printed to suggest a fix.

**Comment by micaelbergeron** [comment]
@nilslice that's perfect thanks!
