### ISSUE TITLE
Should improve error message when no passing config key

### ISSUE THREAD

**Issue by linonetwo** [extism/extism#298]
Plugin content

```rs
use extism_pdk::*;
// use openai::{completions::Completion, set_key};
use serde::Serialize;
use tokio::runtime;

#[plugin_fn]
pub fn openai(input: String) -> FnResult<String> {
  let api_key = config::get("api_key").expect("apikey set in config");

  let prompt = "Say hello";

  let rt = runtime::Builder::new_current_thread().build()?;
  rt.block_on(async {
    // let completion = Completion::builder("text-davinci-003")
    //   .prompt(prompt)
    //   .max_tokens(1024)
    //   .create()
    //   .await
    //   .unwrap()
    //   .unwrap();

    Ok(api_key)
  })
}
```

run with 

```sh
cargo build --release --target wasm32-unknown-unknown && extism call target/wasm32-unknown-unknown/release/memelooop_plugin_openai.wasm openai --input "this is a test" --config aaa=myValue
```

will have error

```
﻿﻿   Compiling memelooop-plugin-openai v0.1.0 (/Users/linonetwo/Desktop/repo/memeloop/memeloop-plugin-examples/memelooop-plugin-openai)
warning: unused variable: `prompt`
  --> src/lib.rs:55:7
   |
55 |   let prompt = "Say hello";
   |       ^^^^^^ help: if this is intentional, prefix it with an underscore: `_prompt`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `input`
  --> src/lib.rs:51:15
   |
51 | pub fn openai(input: String) -> FnResult<String> {
   |               ^^^^^ help: if this is intentional, prefix it with an underscore: `_input`

warning: `memelooop-plugin-openai` (lib) generated 2 warnings
    Finished release [optimized] target(s) in 1.72s
extism_runtime::sdk ERROR 2023-03-28T13:09:26.221118+08:00 - Call: error while executing at wasm backtrace:
    0: 0x1b174 - <unknown>!__rust_start_panic
    1: 0x1b054 - <unknown>!rust_panic
    2: 0x1b024 - <unknown>!std::panicking::rust_panic_with_hook::ha23c8ba67d558e34
    3: 0x1a6d4 - <unknown>!std::panicking::begin_panic_handler::{{closure}}::h17240ff11865f8cf
    4: 0x1a5fe - <unknown>!std::sys_common::backtrace::__rust_end_short_backtrace::h4c1464e549336429
    5: 0x1ac7b - <unknown>!rust_begin_unwind
    6: 0x1bd3f - <unknown>!core::panicking::panic_fmt::h573ffd15dee74109
    7: 0x21a27 - <unknown>!core::panicking::panic_display::h841fa5626059a29b
    8: 0x218e7 - <unknown>!core::panicking::panic_str::h7c1f6e559acd8011
    9: 0x218b5 - <unknown>!core::option::expect_failed::h040ee3c555851d85
   10: 0x7241 - <unknown>!openai
note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information

Caused by:
    wasm trap: wasm `unreachable` instruction executed
Traceback (most recent call last):
  File "/usr/local/bin/extism", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/extism_cli/__init__.py", line 602, in main
    r = plugin.call(args.function, input, parse=None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/extism/extism.py", line 378, in call
    self._check_error(
  File "/usr/local/lib/python3.11/site-packages/extism/extism.py", line 337, in _check_error
    raise Error(_ffi.string(error).decode())
extism.extism.Error: Call failed

Caused by:
    0: error while executing at wasm backtrace:
           0: 0x1b174 - <unknown>!__rust_start_panic
           1: 0x1b054 - <unknown>!rust_panic
           2: 0x1b024 - <unknown>!std::panicking::rust_panic_with_hook::ha23c8ba67d558e34
           3: 0x1a6d4 - <unknown>!std::panicking::begin_panic_handler::{{closure}}::h17240ff11865f8cf
           4: 0x1a5fe - <unknown>!std::sys_common::backtrace::__rust_end_short_backtrace::h4c1464e549336429
           5: 0x1ac7b - <unknown>!rust_begin_unwind
           6: 0x1bd3f - <unknown>!core::panicking::panic_fmt::h573ffd15dee74109
           7: 0x21a27 - <unknown>!core::panicking::panic_display::h841fa5626059a29b
           8: 0x218e7 - <unknown>!core::panicking::panic_str::h7c1f6e559acd8011
           9: 0x218b5 - <unknown>!core::option::expect_failed::h040ee3c555851d85
          10: 0x7241 - <unknown>!openai
       note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information
    1: wasm trap: wasm `unreachable` instruction executed
```

which is very unfriendly.

P.S. run with `cargo build --release --target wasm32-unknown-unknown && extism call target/wasm32-unknown-unknown/release/memelooop_plugin_openai.wasm openai --input "this is a test" --config api_key=myValue` won't have error.

**Comment by nilslice** [comment]
Thanks, @linonetwo -- great point about the error message. In this case the backtrace has pointed to `core::option::expect_failed::h040ee3c555851d85` which hopefully helped enough to get you back to your source code and see that the `expect` function call failed. 

We'll track this issue and see where we can improve error messages as much as possible. You might be able to do some logging here though, and when you write Rust, it can be helpful to handle your own errors, versus using a `unwrap` or `expect` which will cause your code to panic if the error case is encountered. 

```rust
if let Some(key) = config::get("api_key") {
  // use the `key`
} else {
  // log an error
}
```

this is an example of an `if let` binding, which matches on the `Option` value returned from `config::get`. Hope it helps!
