### ISSUE TITLE
Extism panics on Windows

### ISSUE THREAD

**Issue by mhmd-azeez** [extism/extism#299]
While working on #239 I have found out that the runtime published on nuget panics when creating new contexts.

Repro:
```csharp
using Extism.Sdk.Native;

Console.WriteLine($"Version: {Context.GetExtismVersion()}");

using var context = new Context(); // The panic happens here
```

**Download full repro: [panic_bug.zip](https://github.com/extism/extism/files/11093619/panic_bug.zip)**

the [`Context` constructor](https://github.com/extism/extism/blob/300d801d1a31e5cef48f9c96e5881258990f5d71/dotnet/src/Extism.Sdk/Context.cs#L20) calls `extism_context_new`:
```csharp
public Context()
{
    NativeHandle = LibExtism.extism_context_new();
}
```

#### [Extism.runtime.win-x64 v0.4.0](https://www.nuget.org/packages/Extism.runtime.win-x64/0.4.0)

```
Version: 0.3.0
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\std\src\thread\mod.rs:1458:40
stack backtrace:
   0:     0x7ffe81c8cd42 - set_vmctx_memory
   1:     0x7ffe81ca8dfb - set_vmctx_memory
   2:     0x7ffe81c855ea - set_vmctx_memory
   3:     0x7ffe81c8ca8b - set_vmctx_memory
   4:     0x7ffe81c8f3b9 - set_vmctx_memory
   5:     0x7ffe81c8f03b - set_vmctx_memory
   6:     0x7ffe81c8fc50 - set_vmctx_memory
   7:     0x7ffe81c8f99b - set_vmctx_memory
   8:     0x7ffe81c8d75f - set_vmctx_memory
   9:     0x7ffe81c8f690 - set_vmctx_memory
  10:     0x7ffe81d58be5 - _jit_debug_register_code
  11:     0x7ffe81d58c9c - _jit_debug_register_code
  12:     0x7ffe81595270 - extism_version
  13:     0x7ffe8158085d - extism_version
  14:     0x7ffe815787a0 - extism_version
  15:     0x7ffe81580516 - extism_version
  16:     0x7fff518d3a83 - _sys_nerr
  17:     0x7fff518a006e - o_free
  18:     0x7fff5189da1d - execute_onexit_table
  19:     0x7ffe81d1fcf9 - _jit_debug_register_code
  20:     0x7ffe81d1fe1e - _jit_debug_register_code
  21:     0x7fff53eb868f - RtlActivateActivationContextUnsafeFast
  22:     0x7fff53ee1096 - LdrShutdownProcess
  23:     0x7fff53ee0c8d - RtlExitUserProcess
  24:     0x7fff51f882bb - ExitProcess
  25:     0x7fff5189bac0 - exit
  26:     0x7fff5189bcd9 - exit
  27:     0x7ff6d8cb421f - <unknown>
  28:     0x7fff51f826bd - BaseThreadInitThunk
  29:     0x7fff53eea9f8 - RtlUserThreadStart
```

#### [Extism.runtime.win-x64 v0.3.0](https://www.nuget.org/packages/Extism.runtime.win-x64/0.3.0)
```
Version: 0.2.0
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\std\src\thread\mod.rs:1451:9
stack backtrace:
   0:     0x7ffe81c9fa32 - set_vmctx_memory
   1:     0x7ffe81cbbe5b - set_vmctx_memory
   2:     0x7ffe81c97baa - set_vmctx_memory
   3:     0x7ffe81c9f77b - set_vmctx_memory
   4:     0x7ffe81ca2109 - set_vmctx_memory
   5:     0x7ffe81ca1d8a - set_vmctx_memory
   6:     0x7ffe81ca2991 - set_vmctx_memory
   7:     0x7ffe81ca26da - set_vmctx_memory
   8:     0x7ffe81ca045f - set_vmctx_memory
   9:     0x7ffe81ca23e0 - set_vmctx_memory
  10:     0x7ffe81d64275 - _jit_debug_register_code
  11:     0x7ffe81d6436c - _jit_debug_register_code
  12:     0x7ffe81694580 - extism_version
  13:     0x7ffe815fc02d - extism_version
  14:     0x7ffe815e6e61 - extism_version
  15:     0x7ffe815fbddb - extism_version
  16:     0x7fff518d3a83 - _sys_nerr
  17:     0x7fff518a006e - o_free
  18:     0x7fff5189da1d - execute_onexit_table
  19:     0x7ffe81d2d419 - _jit_debug_register_code
  20:     0x7ffe81d2d53e - _jit_debug_register_code
  21:     0x7fff53eb868f - RtlActivateActivationContextUnsafeFast
  22:     0x7fff53ee1096 - LdrShutdownProcess
  23:     0x7fff53ee0c8d - RtlExitUserProcess
  24:     0x7fff51f882bb - ExitProcess
  25:     0x7fff5189bac0 - exit
  26:     0x7fff5189bcd9 - exit
  27:     0x7ff70730421f - <unknown>
  28:     0x7fff51f826bd - BaseThreadInitThunk
  29:     0x7fff53eea9f8 - RtlUserThreadStart
```

#### [Extism.runtime.win-x64 v0.2.0](https://www.nuget.org/packages/Extism.runtime.win-x64/0.2.0)
```
Version: 0.1.0
```

Note: The nuget version is ahead of the extism runtime version by 1 because of a stupid mistake I made while creating the GitHub actions.

**Comment by nilslice** [comment]
Thanks, @mhmd-azeez! We're looking into this.

**Comment by zshipko** [comment]
It seems to be some kind of issue when the timer is cleaned up using `atexit` - I'm not sure exactly sure beyond that, but this branch seems to work correctly on Windows now: https://github.com/extism/extism/tree/fix-runtime-on-windows

@mhmd-azeez when you get a moment can you test out that branch and let me know if it works for you?

**Comment by mhmd-azeez** [comment]
Hello @zshipko, I built libextism using this command:
```
cargo build --release --target "x86_64-pc-windows-msvc" -p libextism
```
and tried it out on the `fix-runtime-on-windows` branch and it doesn't panic anymore
