### ISSUE TITLE
The runtime only returns a generic error when calling `extism_plugin_error`

### ISSUE THREAD

**Issue by mhmd-azeez** [extism/extism#567]
Plugin:
```
package main

import "github.com/extism/go-pdk"

//export run_test
func run_test() int32 {
	pdk.SetErrorString("my custom error")
	return 1
}

func main() {}
```

Host:
```
[Fact]
public unsafe void Exception()
{
    var manifest = new Manifest(new PathWasmSource(@"D:\dylibso\go-sdk\plugins\noop\throw.wasm"));
    using var plugin = new Plugin(manifest, Array.Empty<HostFunction>(), withWasi: true);

    fixed (byte* dataPtr = Array.Empty<byte>())
    {
        int response = LibExtism.extism_plugin_call(plugin.NativeHandle, "run_test", dataPtr, 0);

        var errPtr = LibExtism.extism_plugin_error(plugin.NativeHandle);
        var errorMsg = Marshal.PtrToStringUTF8(errPtr);

        errorMsg.ShouldContain("my custom error");
    }
}
```

```
PS D:\dylibso\dotnet-sdk> dotnet test --filter "Exception"
  Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.28]     Extism.Sdk.Tests.BasicTests.Exception [FAIL]
  Failed Extism.Sdk.Tests.BasicTests.Exception [130 ms]
  Error Message:
   Shouldly.ShouldAssertException : errorMsg
    should contain (case insensitive comparison)
"my custom error"
    but was actually
"Error in Extism plugin call"
  Stack Trace:
     at Extism.Sdk.Tests.BasicTests.Exception() in D:\dylibso\dotnet-sdk\test\Extism.Sdk\BasicTests.cs:line 96
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - Extism.Sdk.Tests.dll (net7.0)
```

It works as expected in the Go SDK:
```
PS D:\dylibso\go-sdk\plugins\noop> extism call .\throw.wasm run_test --wasi
Error: my custom error
```

I tried out this test:
```
const THROW: &[u8] = include_bytes!("D:/dylibso/go-sdk/plugins/noop/throw.wasm");
#[test]
fn test_throw() {
    let manifest = Manifest::new([extism_manifest::Wasm::data(THROW)]);
    let mut plugin = Plugin::new_with_manifest(&manifest, [], true).unwrap();
    let output: Result<String, Error> = plugin.call("run_test", "");
    assert!(output.is_err());
    assert_eq!(output.unwrap_err().root_cause().to_string(), "my custom error");
}
```
And it seems to be working, so I am guessing the problem is in `sdk.rs`. or maybe I am using the sdk incorrectly

**Comment by mhmd-azeez** [comment]
cc @zshipko
