### ISSUE TITLE
Extism gem fails to load on Ruby 3.3.0 on macOS

### ISSUE THREAD

**Issue by brandondrew** [extism/extism#695]
The extism gem throws an error immediately after trying to require the library:

```
brandon@Air ~ % gem install extism
Successfully installed extism-1.0.0
Parsing documentation for extism-1.0.0
Done installing documentation for extism after 0 seconds
1 gem installed

brandon@Air ~ % irb

irb(main):001> require 'extism'
/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ffi-1.16.3/lib/ffi/dynamic_library.rb:65:in `load_library': Could not open library 'extism': dlopen(extism, 0x0005): tried: 'extism' (no such file), '/usr/local/lib/extism' (no such file), '/usr/lib/extism' (no such file), '/Users/brandon/extism' (no such file). (LoadError)
Could not open library 'libextism.dylib': dlopen(libextism.dylib, 0x0005): tried: 'libextism.dylib' (no such file), '/usr/local/lib/libextism.dylib' (no such file), '/usr/lib/libextism.dylib' (no such file), '/Users/brandon/libextism.dylib' (no such file).
Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib, /opt/homebrew/lib
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ffi-1.16.3/lib/ffi/library.rb:95:in `block in ffi_lib'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ffi-1.16.3/lib/ffi/library.rb:94:in `map'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ffi-1.16.3/lib/ffi/library.rb:94:in `ffi_lib'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/extism-1.0.0/lib/extism/libextism.rb:8:in `<module:LibExtism>'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/extism-1.0.0/lib/extism/libextism.rb:6:in `<module:Extism>'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/extism-1.0.0/lib/extism/libextism.rb:1:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/extism-1.0.0/lib/extism.rb:7:in `require_relative'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/extism-1.0.0/lib/extism.rb:7:in `<top (required)>'
	from <internal:/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `require'
	from <internal:/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `rescue in require'
	from <internal:/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:135:in `require'
	from (irb):1:in `<main>'
	from <internal:kernel>:187:in `loop'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/irb-1.11.2/exe/irb:9:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.3.0/bin/irb:25:in `load'
	from /Users/brandon/.rbenv/versions/3.3.0/bin/irb:25:in `<main>'
<internal:/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- extism (LoadError)
	from <internal:/Users/brandon/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from (irb):1:in `<main>'
	from <internal:kernel>:187:in `loop'
	from /Users/brandon/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/irb-1.11.2/exe/irb:9:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/3.3.0/bin/irb:25:in `load'
	from /Users/brandon/.rbenv/versions/3.3.0/bin/irb:25:in `<main>'
irb(main):002> 
```

**Comment by brandondrew** [comment]
Oops! Missed the `sudo extism lib install` step, and the fact that there were off-page steps needed:

```
curl https://get.extism.org/cli | sh
```

**Comment by nilslice** [comment]
hey @brandondrew! glad you got it working 

> there were off-page steps needed

do you recall which of these steps weren't on the doc you used to get started? would like to fix that

**Comment by brandondrew** [comment]
It might make sense to include the missing `curl` step on that page (even though there are other options), to make it easier to follow the directions as a simple step-by-step process (and allow those who want to dig into the alternative methods to follow the link).

It so common for READMEs to include several different pages (do this on Red Hat, this on Ubuntu, this on Windows, this on Mac, etc.) that I tend to scan the commands and mentally filter out the ones that don't seem to apply.  In this case that strategy failed me.

**Comment by brandondrew** [comment]
@nilslice yeah, the `curl` step was not on the page I was reading: https://extism.org/docs/quickstart/host-quickstart

**Comment by brandondrew** [comment]
You could just include a note next to the `curl` step that building from source and using Nix are also alternative options.

**Comment by nilslice** [comment]
I see, thanks! Yea, linking to a single page is really an effort for us to reduce the amount of changes needed in case the curl install instructions change. will bring it up to the team and see - appreciate your feedback!
