### ISSUE TITLE
PHP Host-SDK: Cannot parse libextism.dylib

### ISSUE THREAD

**Issue by bhelx** [extism/extism#96]
Running into an issue on mac when the FFIMe library tries to recursively resolve symbols in libextism.dylib:

```
PHP Warning:  file_get_contents(/System/Library/Frameworks/Security.framework/Versions/A/Security): Failed to open stream: No such file or directory in /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/Parser.php on line 18

Warning: file_get_contents(/System/Library/Frameworks/Security.framework/Versions/A/Security): Failed to open stream: No such file or directory in /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/Parser.php on line 18
PHP Fatal error:  Uncaught LogicException: File is neither in ELF nor Mach-O format in /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/Parser.php:28
Stack trace:
#0 /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/MachO/ObjectFile.php(50): PHPObjectSymbolResolver\Parser::parseFor('/System/Library...')
#1 /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/MachO/ObjectFile.php(59): PHPObjectSymbolResolver\MachO\ObjectFile->resolveDependentObjectsRecursively()
#2 /private/tmp/extism-php/vendor/ircmaxell/ffime/lib/FFIMe.php(86): PHPObjectSymbolResolver\MachO\ObjectFile->getAllSymbolsRecursively()
#3 /private/tmp/extism-php/vendor/extism/extism/php/src/Context.php(8): FFIMe\FFIMe->__construct('libextism.dylib')
#4 /private/tmp/extism-php/vendor/extism/extism/php/src/Context.php(29): Extism\generate_extism_lib()
#5 /private/tmp/extism-php/vendor/composer/autoload_real.php(55): require('/private/tmp/ex...')
#6 /private/tmp/extism-php/vendor/composer/autoload_real.php(38): composerRequire86fe5302a9cb56b04c03c0b0891eaa17('2e9cc0389558e6d...', '/private/tmp/ex...')
#7 /private/tmp/extism-php/vendor/autoload.php(25): ComposerAutoloaderInit86fe5302a9cb56b04c03c0b0891eaa17::getLoader()
#8 /private/tmp/extism-php/index.php(3): require_once('/private/tmp/ex...')
#9 {main}
  thrown in /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/Parser.php on line 28

Fatal error: Uncaught LogicException: File is neither in ELF nor Mach-O format in /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/Parser.php:28
Stack trace:
#0 /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/MachO/ObjectFile.php(50): PHPObjectSymbolResolver\Parser::parseFor('/System/Library...')
#1 /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/MachO/ObjectFile.php(59): PHPObjectSymbolResolver\MachO\ObjectFile->resolveDependentObjectsRecursively()
#2 /private/tmp/extism-php/vendor/ircmaxell/ffime/lib/FFIMe.php(86): PHPObjectSymbolResolver\MachO\ObjectFile->getAllSymbolsRecursively()
#3 /private/tmp/extism-php/vendor/extism/extism/php/src/Context.php(8): FFIMe\FFIMe->__construct('libextism.dylib')
#4 /private/tmp/extism-php/vendor/extism/extism/php/src/Context.php(29): Extism\generate_extism_lib()
#5 /private/tmp/extism-php/vendor/composer/autoload_real.php(55): require('/private/tmp/ex...')
#6 /private/tmp/extism-php/vendor/composer/autoload_real.php(38): composerRequire86fe5302a9cb56b04c03c0b0891eaa17('2e9cc0389558e6d...', '/private/tmp/ex...')
#7 /private/tmp/extism-php/vendor/autoload.php(25): ComposerAutoloaderInit86fe5302a9cb56b04c03c0b0891eaa17::getLoader()
#8 /private/tmp/extism-php/index.php(3): require_once('/private/tmp/ex...')
#9 {main}
  thrown in /private/tmp/extism-php/vendor/ircmaxell/php-object-symbolresolver/lib/Parser.php on line 28
  ```
  
  
This is happening on an M1 Mac (macOS 12.5.1).  It appears that macOS is injecting these links to these security shared libraries in the libextism.dylib:

```
$ otool -L /usr/local/lib/libextism.dylib
/usr/local/lib/libextism.dylib:
	/Users/runner/work/extism/extism/target/aarch64-apple-darwin/release/deps/libextism.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60157.60.19)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1856.105.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```
  
  This [php symbol resolver library](https://github.com/ircmaxell/php-object-symbolresolver) that FFIMe uses does seem to know how to resolve these. 
  
I tried compiling libextism.dylib myself as well as pulling down the pre-built binaries and they are still there.

**Comment by mhmd-azeez** [comment]
@bhelx can you please try again with the latest changes in https://github.com/extism/php-sdk/pull/7?

**Comment by zshipko** [comment]
Closing this since FFIMe is no longer used in the php sdk
